name: Reloj Diario Notificaciones Polizas

on:
  schedule:
    # 16:00 UTC equivale a las 11:00 AM hora de Ecuador (UTC-5)
    - cron: "0 16 * * *"
  workflow_dispatch: 

jobs:
  ejecutar-notificaciones:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ejecutar Script de Notificaciones
        run: node cron-notificaciones.js
